// Generated by CoffeeScript 1.3.3
(function() {
  var myapp;

  myapp = angular.module('myapp', ['firebase']);

  myapp.directive('draggable', function() {
    return {
      restrict: 'A',
      scope: {
        shape: '='
      },
      link: function(scope, element, attrs) {
        var lastPos, moving;
        moving = false;
        $(element).mousedown(function(event) {
          return moving = true;
        });
        $(document).mouseup(function(event) {
          return moving = false;
        });
        lastPos = null;
        return $(document).bind('mousemove', function(event) {
          var pos;
          if (moving) {
            pos = {
              x: event.clientX,
              y: event.clientY
            };
            if (lastPos) {
              if (event.metaKey) {
                console.log('size');
                scope.shape.size += pos.x - lastPos.x;
              } else {
                scope.shape.x += pos.x - lastPos.x;
                scope.shape.y += pos.y - lastPos.y;
              }
              scope.$apply();
            }
            return lastPos = pos;
          }
        });
      }
    };
  });

  myapp.controller('MyCtrl', [
    '$scope', 'angularFire', function($scope, angularFire) {
      var url;
      url = 'https://latentflip.firebaseio.com/shapes';
      $scope.shapes = angularFire(url, $scope, 'shapes', []);
      return $scope.shapes.then(function() {
        var s, _i, _len, _ref;
        _ref = $scope.shapes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          s.size || (s.size = 10);
        }
        return $scope.addShape = function() {
          return $scope.shapes.push({
            x: 5,
            y: 5,
            size: 10
          });
        };
      });
    }
  ]);

}).call(this);
